### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by pklimowx** [intel/kubernetes-power-manager#10]
During deployment, I found the README file really confusing. I prepare some suggestions for you which you may find useful:

* remove yaml files from readme and put links to examples - with that you will get rid of outdated code
* in sections that describe components it can be stated clearly what is and what is not deployed directly by the operator  
* be consistent with names - if, for example, the section is about PowerConfig use `Power Config` as a title and not `Config Controller` and stick to it in the whole text - this will help us, users, understand faster what's going on there
* in the shared PowerProfile we can read: `giving more room for different configurations, but these configurations are not explained clearly - I would say that `Shared` config should have a separate section so it won't mix with the default one
* use Power Manager instead of Power Operator and not both. Sometimes Power Controller is used as well and the pod's name is `controller-manager` - consistency is the key here I think

**Comment by patricia-cahill** [comment]
ReadME updated
