### ISSUE TITLE
Pods with "Completed" status (after running Jobs) are not getting exclusive CPU allocations removed

### ISSUE THREAD

**Issue by Feelas** [intel/kubernetes-power-manager#20]
**Description**
We're constantly seeing that CPU allocations are not cleaned up after running Jobs and only after Pods with "Completed" status are removed. This is unwieldy for running Jobs Pods on a cluster if they have a performance class scheduled, because it causes stall of proper Power Node Agent operation.

**Reproduction tips**
1. Create and run a K8s job
2. Observe that pods are not being removed, while both Pods CpuIDs are kept in PowerWorkloads, despite pods no longer being running (I assume that CPU Manager doesn't hold the allocations either).

**Possible cause**
I might be wrong with this, but the Reconcile loop in PowerPod controller stops if Pods are not "Running" status nor being deleted (DeletionTimestamp checks). As such, it is impossible to remove cores used by pods in "Completed" status.
I believe modifying the behavior of "Phase == corev1.PodRunning" condition to account for pods from Completed jobs could fix the issue. The line I'm mentioning is permalinked here https://github.com/intel/kubernetes-power-manager/blob/64a5662c34004767808e74abe957fc016b878f59/controllers/powerpod_controller.go#L149

**Comment by patricia-cahill** [comment]
> Hello, is this fixed yet in v2.1.0?

Hey @Feelas, this issue was address and fixed in v2.1.0  
If you have any other problems please reach out.
