### ISSUE TITLE
Communication Channels?

### ISSUE THREAD

**Issue by asim-reza** [intel/kubernetes-power-manager#21]
Hey Everyone!
I wanted to contribute to this project as well as intel/edge-conductor... But as is the case for the main K8s project I couldnt find means to communicate and coordinate with other contributors , e.g slack... I was wondering if I just missed it, or there is none, or if so is it internal to intel?

**Comment by patricia-cahill** [comment]
Apologies for the delay, as of now this is the main way to communicate with the team, or you could email us directly, any feedback is greatly apricated.
