### ISSUE TITLE
Link to app qos in README is not working

### ISSUE THREAD

**Issue by vielmetti** [intel/kubernetes-power-manager#4]
The link at this commit

https://github.com/intel/kubernetes-power-manager/blame/84b6c0c80c16f44f7c4b90d0a52b4c355cab1147/README.md#L81

points to App QOS, but the deep link within the repo goes to 404. (I think it's a simple fix because the code is there.)

**Comment by patricia-cahill** [comment]
V2 release does not include App QoS
