### ISSUE TITLE
Enabling the Power Node Agent to run on the control-plane

### ISSUE THREAD

**Issue by ejalberti** [intel/kubernetes-power-manager#40]
This is a proposal of a new feature.

In the actual organization/implementation of the project, the controller-manager is responsible for deploying the Power Node Agent on the nodes where the user chooses to apply the Power Config. However, if the user wants to control the Power configuration of the cluster machine that runs only the K8S Control Plane, the Power Node Agent would not be admitted because of the node role.

An alternative to allow the Power Node Agent to run in a control plane machine, is the addition of a toleration statement in the Power Node Agent deployment file. This change needs to be incorporated on the manifest that resides on controller-manager image, allowing automatic deployment of the DaemonSet.
`tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule`

In order to control the deployment of the Power Node Agent on the Control Plane Machine, an argument can be implemented to enable or disable this ability.

**Comment by adorney99** [comment]
Hi @ejalberti this is a good point. Typically when testing on a control plane node we just remove the taint but something more fine grained like this would be a lot more practical. We can take a look at adding something like this in a future release if we have some extra cycles

**Comment by adorney99** [comment]
closing issue as a backlog story was generated to track implementing this
