### ISSUE TITLE
Clean up git history

### ISSUE THREAD

**Issue by marquiz** [intel/kubernetes-power-manager#5]
I would suggest to squash the git history in order to clean up the issues there. Possibly into just a single commit. For example 4a754d5a798069a9e4af69f03d408bfdbba10835 commits a huge 42MB binary (executable) blob that unnecessary bloats the repo.

If you don't want to change master I suggest to push the squashed history into a new `main` branch, make it the default branch (and just delete `master` later on)

**Comment by patricia-cahill** [comment]
Done, Thanks
