### ISSUE TITLE
Incorrect log string causes dpanic log when log level 5 enabled for controller-manager pod

### ISSUE THREAD

**Issue by bartwensley** [intel/kubernetes-power-manager#55]
I enabled log level 5 for the controller-manager pod and this causes a dpanic log when pods are started. For example:
`
{"level":"dpanic","ts":"2023-08-14T13:54:41Z","logger":"controllers.PowerPod","msg":"odd number of arguments passed as key-value pairs for logging","powerpod":"my-namespace/my-pod-hlk8g","ignored key":[],"stacktrace":"github.com/intel/kubernetes-power-manager/controllers.getContainersRequestingExclusiveCPUs\n\t/workspace/controllers/powerpod_controller.go:411\ngithub.com/intel/kubernetes-power-manager/controllers.(*PowerPodReconciler).Reconcile\n\t/workspace/controllers/powerpod_controller.go:156\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
`

This is due to an incorrect log string on this line: https://github.com/intel/kubernetes-power-manager/blob/289c3c2c0de2a4b14bdddfbac4a7718570c85aee/controllers/powerpod_controller.go#L411C1-L411C1

**Comment by adorney99** [comment]
Thanks for pointing this out. We've got a couple of these log lines scattered throughout the codebase that we're working on tidying up

**Comment by adorney99** [comment]
closing as log messages were refactored
