### ISSUE TITLE
Feature Request: allow power configuration for reserved CPUs

### ISSUE THREAD

**Issue by bartwensley** [intel/kubernetes-power-manager#63]
When a shared PowerWorkload is created (see https://github.com/intel/kubernetes-power-manager/blob/master/examples/example-shared-workload.yaml) the reservedCPUs are specified and are excluded when the shared PowerProfile is applied to the system (by design). There are usecases where a user may want to tune the c-states/p-states for the reservedCPUs differently than the rest of the system (e.g. to bump up their frequency or to change their cpufreq governor). I know that can be done outside of KPM, but it would be better to allow this to be done by KPM itself so a single component is responsible for the power related configuration of all CPUs on the host.

One option would be to allow a different PowerProfile to be applied these reservedCPUs. The request is to allow any of the supported power settings (epp, governor, max/min frequency, c-states) to be configured specifically for these reservedCPUs.

**Comment by adorney99** [comment]
closing this issue as reserved pool frequency tuning was added in latest release
