### ISSUE TITLE
Feature Request: Allow a PowerProfile to be specified for multiple containers in the same pod

### ISSUE THREAD

**Issue by bartwensley** [intel/kubernetes-power-manager#64]
The KPM only allows a PowerProfile to be specified for a single container in a pod. There are use cases where there are multiple containers in the same pod. This request is to enhance KPM to allow a PowerProfile to (optionally) be specified for more than one container in the same pod.

The config would be identical to what is already supported - for each container in a pod, allow "power.intel.com/<POWER_PROFILE>" requests/limits to be specified. Today the code raises an error if the request/limit is specified for more than one container in the same pod.

**Comment by adorney99** [comment]
closing issue as this feature was added in the latest release
