### ISSUE TITLE
Default Max and Min frequency for base profiles

### ISSUE THREAD

**Issue by sahanirn** [intel/kubernetes-power-manager#68]
@adorney99 How are the max and min frequencies for the base profiles (performance, balance-power, balance-performance) set? Does it depend on any hardware characteristics or is it defined somewhere within intel power manager? If defined, can we change them before deployment, without having to edit later.

**Comment by adorney99** [comment]
Hi @sahanirn, The values used are based on hardware frequency ranges. The frequency values are calculated by getting the system frequency range (total max - total min), taking a set percentage of that value and subtracting it from the maximum core frequency. The min is just this value minus 200. 

We don't have any user facing method of changing these values as users can create their own custom profiles but if you're alright with building images locally you can edit the percentages [here](https://github.com/intel/kubernetes-power-manager/blob/dd1ae26633f95788325064502887b8bd4627c0ea/controllers/powerprofile_controller.go#L52) to change the percentages used. For example balance performance takes 25% of the system frequency range and subtracts it from the system max frequency
